package models;
// Generated 16-Jan-2019 11:22:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Applicant generated by hbm2java
 */
@Entity
@Table
public class Applicant implements java.io.Serializable {

    private int nationalId;
    private String firstName;
    private String lastName;
    private int phone;
    private String email;
    private byte[] tenderDocument;
    private boolean approved;
    private User users;

    public Applicant() {
    }

    public Applicant(int nationalId, String firstName, String lastName, int phone, String email, byte[] tenderDocument, boolean approved, User users) {
        this.nationalId = nationalId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.tenderDocument = tenderDocument;
        this.approved = approved;
        this.users = users;
    }

    public Applicant(int nationalId, String firstname, String lastname, int phone, String email, byte[] document, boolean b) {
        this.nationalId = nationalId;
        this.firstName = firstname;
        this.lastName = lastname;
        this.phone = phone;
        this.email = email;
        this.tenderDocument = document;
        this.approved = b;
    }

    @Id
    @Column(name = "national_id", nullable = false, length = 8)
    public int getNationalId() {
        return this.nationalId;
    }

    public void setNationalId(int nationalId) {
        this.nationalId = nationalId;
    }

    @Column(name = "first_name", nullable = false, length = 15)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", nullable = false, length = 15)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "phonenumber", nullable = false, length = 10)
    public int getPhone() {
        return this.phone;
    }

    public void setPhone(int phone) {
        this.phone = phone;
    }

    @Column(name = "email", nullable = false, length = 20)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "document", nullable = false)
    public byte[] getTenderDocument() {
        return this.tenderDocument;
    }

    public void setTenderDocument(byte[] tenderDocument) {
        this.tenderDocument = tenderDocument;
    }

    @Column(name = "approved", nullable = false)
    public boolean isApproved() {
        return this.approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }

    @OneToOne(optional = true)
    public User getUsers() {
        return this.users;
    }

    public void setUsers(User users) {
        this.users = users;
    }

}
