package models;
// Generated Jan 4, 2019 9:50:41 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private int nationalId;
     private String password;
     private String role;
     

    public User() {
    }

	
    public User(String username, String password, int nationalId, String role) {
        this.username = username;
        this.nationalId = nationalId;
        this.role = role;
        this.password = password;
    }

   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public int getNationalId() {
        return nationalId;
    }

    public void setNationalId(int nationalId) {
        this.nationalId = nationalId;
    }
    
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


